/*
 *   This file was AUTO-GENERATED by pypgmopts.
 *
 *   https://github.com/johndoe31415/pypgmopts
 *
 *   Do not edit it by hand, your changes will be overwritten.
 *
 *   Generated at: 2019-10-23 20:13:13
 */

#ifndef __ARGPARSE_CLIENT_H__
#define __ARGPARSE_CLIENT_H__

#include <stdbool.h>

#define ARGPARSE_CLIENT_DEFAULT_PORT		23170
#define ARGPARSE_CLIENT_DEFAULT_VERBOSE		0

#define ARGPARSE_CLIENT_NO_OPTION		0
#define ARGPARSE_CLIENT_POSITIONAL_ARG	1

enum argparse_client_option_t {
	ARG_CLIENT_PORT = 2,
	ARG_CLIENT_VERBOSE = 3,
	ARG_CLIENT_FILENAME = 4,
	ARG_CLIENT_HOSTNAME = 5,
};

typedef void (*argparse_client_errmsg_callback_t)(const char *errmsg, ...);
typedef void (*argparse_client_errmsg_option_callback_t)(enum argparse_client_option_t error_option, const char *errmsg, ...);
typedef bool (*argparse_client_callback_t)(enum argparse_client_option_t option, const char *value, argparse_client_errmsg_callback_t errmsg_callback);
typedef bool (*argparse_client_plausibilization_callback_t)(argparse_client_errmsg_option_callback_t errmsg_callback);

bool argparse_client_parse(int argc, char **argv, argparse_client_callback_t argument_callback, argparse_client_plausibilization_callback_t plausibilization_callback);
void argparse_client_show_syntax(void);
void argparse_client_parse_or_quit(int argc, char **argv, argparse_client_callback_t argument_callback, argparse_client_plausibilization_callback_t plausibilization_callback);

#endif
