#!/bin/bash
#
#

VERSION="1.1.0e"
URL="https://www.openssl.org/source/openssl-${VERSION}.tar.gz"
LOCAL_TARGZ="openssl-${VERSION}.tar.gz"
LOCAL_DIR="openssl-${VERSION}"

if [ ! -f "$LOCAL_TARGZ" ]; then
	wget "$URL"
fi

if [ ! -d "$LOCAL_DIR" ]; then
	tar xfz "$LOCAL_TARGZ"
	cd "$LOCAL_DIR"
	./config
	make -j 16
fi
