#!/bin/sh
#
# Initramfs-tools hook script for remote LUKS unlocking
#
# Copyright 2016-2022 Johannes Bauer <joe@johannes-bauer.com>
# Released under GPLv3

PREREQ=""

prereqs()
{
	echo "$PREREQ"
}

case $1 in
	prereqs)
		prereqs
		exit 0
		;;
esac

. /usr/share/initramfs-tools/hook-functions

if [ ! -f /etc/luksrku-client.bin ]; then
	exit 0
fi
cp /etc/luksrku-client.bin ${DESTDIR}/etc/
if [ -f /etc/luksrku.conf ]; then
	cp /etc/luksrku.conf ${DESTDIR}/etc/
fi
copy_exec /usr/local/sbin/luksrku /sbin
