#!/bin/sh
#
# Copyright 2016-2019 Johannes Bauer <joe@johannes-bauer.com>
# Released under GPLv3

PREREQ="lvm2"

#
# Standard initramfs preamble
#
prereqs()
{
	echo "$PREREQ"
}

case $1 in
	prereqs)
		prereqs
		exit 0
		;;
esac

. /scripts/functions

if [ ! -f /etc/luksrku-client.bin ]; then
	exit 0
fi

configure_networking
/sbin/luksrku client -v /etc/luksrku-client.bin

exit 0
